resources:
  - deployment.yaml

configMapGenerator:
  - name: sequence-config
    files:
      - config.yaml
  - name: scaling-config
    files:
      - config-scaling.yaml

generatorOptions:
  disableNameSuffixHash: true